services:

  pcap-reader:
    image: python:3.9-slim
    container_name: pcap-reader
    volumes:
      - ./app:/usr/src/app        # Monta o diretório local 'app' dentro do container
      - ./soc:/usr/src/soc    # Monta o diretório com os arquivos PCAP
    working_dir: /usr/src/soc
    command: python3 pcap_reader.py  # Executa o script Python de leitura de PCAPs
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - appdata:/var/www
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - frontend
      - backend

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - fazenda_pg_data:/bitnami/postgresql
    networks:
      - backend

volumes:
  appdata:
  fazenda_pg_data:

networks:
  frontend:
  backend:
