services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5000:5432'

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2000M'

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - fazenda_pg_data:/bitnami/postgresql

    networks:
      - backend

  soc:
    build:
      context: ./soc

    volumes:
      - ./soc:/usr/src/soc

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2000M'

    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    
    depends_on:
      - postgres

    privileged: true

    ports:
      - '3000:3000'

    networks:
      - backend
    
    restart: unless-stopped

  app:
    build:
      context: ./app

    image: digitalocean.com/flask-python:3.6

    volumes:
      - ./app:/usr/src/app

    ports:
      - '8080:8080'

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2000M'

    depends_on:
      - soc

    networks:
      - backend
    
    restart: unless-stopped

    

networks:
  backend:

volumes:
  fazenda_pg_data: