services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      POSTGRES_DB: fazenda
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - appdata:/var/www
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    networks:
      - frontend
      - backend

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fazenda
    volumes:
      - fazenda_pg_data:/bitnami/postgresql
    networks:
      - backend

volumes:
  appdata:
  fazenda_pg_data:

networks:
  frontend:
  backend:
